# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40d53439619dfc5ee09b2bc18c7951d786bbd5956a9afd1d7c72289ccfa8c3af25dd6abe9dc819243dca41557c9b4b07c6485091ca734629a6b63b9ad619f4ca

test:
  secret_key_base: e97c8273a80940bb6590154a4692b1fe3098b323fca062a0eb2c149d62cb43e3ee19b4f64033befed04377ad2d33999fcc19475be15361804b369f91a22b4580

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
